In [1]:
%load_ext autoreload
%autoreload 2

# Check data

In [9]:
import pandas as pd

data = pd.read_csv("data/data_train_1k.csv", nrows = None)

In [10]:
data

,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,2009-06-15 17:26:21.0000001,4.5,2009-06-15 17:26:21 UTC,-73.844311,40.721319,-73.841610,40.712278,1
1,2010-01-05 16:52:16.0000002,16.9,2010-01-05 16:52:16 UTC,-74.016048,40.711303,-73.979268,40.782004,1
2,2011-08-18 00:35:00.00000049,5.7,2011-08-18 00:35:00 UTC,-73.982738,40.761270,-73.991242,40.750562,2
3,2012-04-21 04:30:42.0000001,7.7,2012-04-21 04:30:42 UTC,-73.987130,40.733143,-73.991567,40.758092,1
4,2010-03-09 07:51:00.000000135,5.3,2010-03-09 07:51:00 UTC,-73.968095,40.768008,-73.956655,40.783762,1
...,...,...,...,...,...,...,...,...
995,2011-07-30 07:33:13.0000001,16.9,2011-07-30 07:33:13 UTC,-73.884801,40.755707,-73.980472,40.765556,1
996,2011-09-24 23:20:00.000000112,13.7,2011-09-24 23:20:00 UTC,-73.953603,40.779203,-73.995763,40.726701,3
997,2011-12-22 11:07:00.00000037,29.3,2011-12-22 11:07:00 UTC,-73.942380,40.837712,-73.864372,40.769985,2
998,2014-11-03 12:40:00.00000014,6.5,2014-11-03 12:40:00 UTC,-73.961151,40.774578,-73.972251,40.785640,1
999,2012-05-18 18:41:30.0000006,10.9,2012-05-18 18:41:30 UTC,-73.988455,40.758432,-73.983816,40.730147,1

# Check Encoders

In [2]:
from TaxiFareModel.encoders import TimeFeaturesEncoder, DistanceTransformer, AddGeohash, OptimizeSize, Direction, \
    DistanceToCenter

t_encoder = TimeFeaturesEncoder(time_column = 'pickup_datetime')


t_encoder.fit_transform(data[['pickup_datetime']])

/Users/moyang/.pyenv/versions/3.8.5/envs/bubble/lib/python3.8/site-packages/pandas/core/indexing.py:1596: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
/Users/moyang/.pyenv/versions/3.8.5/envs/bubble/lib/python3.8/site-packages/pandas/core/indexing.py:1743: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)

     dow  hour  month  year
0      0    13      6  2009
1      1    11      1  2010
2      2    20      8  2011
3      5     0      4  2012
4      1     2      3  2010
..   ...   ...    ...   ...
995    5     3      7  2011
996    5    19      9  2011
997    3     6     12  2011
998    0     7     11  2014
999    4    14      5  2012

[1000 rows x 4 columns]

In [4]:
dist = DistanceTransformer()

In [5]:
dist.fit_transform(data)

     distance
0    0.009436
1    0.079696
2    0.013674
3    0.025340
4    0.019470
..        ...
995  0.096177
996  0.067334
997  0.103306
998  0.015671
999  0.028663

[1000 rows x 1 columns]

In [6]:
AddGeohash().fit_transform(data)

    geohash_pickup geohash_dropoff
0           dr5rxt          dr5rxe
1           dr5ree          dr72h8
2           dr5ruk          dr5ru6
3           dr5rsr          dr5ru7
4           dr5ruv          dr72j0
..             ...             ...
995         dr5rye          dr5rut
996         dr5rvp          dr5rsn
997         dr72m6          dr5rzj
998         dr5ruy          dr72h8
999         dr5ru7          dr5rsq

[1000 rows x 2 columns]

In [7]:
DistanceToCenter().fit_transform(data)

     pickup_distance_to_center  dropoff_distance_to_center
0                    13.682770                   13.889803
1                     0.874172                    7.881560
2                     5.603895                    4.243449
3                     2.662028                    5.041393
4                     6.800820                    8.799925
..                         ...                         ...
995                  11.237745                    6.117198
996                   8.489483                    1.656639
997                  14.757109                   13.478644
998                   7.723207                    8.451737
999                   5.148787                    2.603101

[1000 rows x 2 columns]

In [8]:
Direction().fit_transform(data)

     delta_lon  delta_lat   direction
0    -0.002701   0.009041  106.633523
1    -0.036780  -0.070701 -117.484306
2     0.008504   0.010708   51.544361
3     0.004437  -0.024949  -79.915791
4    -0.011440  -0.015754 -125.985832
..         ...        ...         ...
995   0.095671  -0.009849   -5.877698
996   0.042160   0.052502   51.234943
997  -0.078008   0.067727  139.035294
998   0.011100  -0.011062  -44.901758
999  -0.004639   0.028285   99.314112

[1000 rows x 3 columns]

# Check `predict.py'

In [6]:
from TaxiFareModel.predict import Predictor

predictor = Predictor(local=True)

model = predictor.get_model()

/Users/moyang/.pyenv/versions/3.8.5/envs/bubble/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator RobustScaler from version 0.24.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/Users/moyang/.pyenv/versions/3.8.5/envs/bubble/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator Pipeline from version 0.24.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/Users/moyang/.pyenv/versions/3.8.5/envs/bubble/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator OneHotEncoder from version 0.24.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/Users/moyang/.pyenv/versions/3.8.5/envs/bubble/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator ColumnTransformer from version 0.24.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(
/Users/moyang/.pyenv/versions/3.8.5/envs/bubble/lib/python3.8/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator Lasso from version 0.24.1 when using version 0.23.2. This might lead to breaking code or invalid results. Use at your own risk.
  warnings.warn(

In [7]:
import pandas as pd

key = "2013-07-06 17:18:00.000000119"
pickup_datetime = "2013-07-06 17:18:00 UTC"
pickup_longitude = "-73.950655"
pickup_latitude = "40.783282"
dropoff_longitude = "-73.984365"
dropoff_latitude = "40.769802"
passenger_count = "1"

X = pd.DataFrame(dict(
        key=[key],
        pickup_datetime=[pickup_datetime],
        pickup_longitude=[float(pickup_longitude)],
        pickup_latitude=[float(pickup_latitude)],
        dropoff_longitude=[float(dropoff_longitude)],
        dropoff_latitude=[float(dropoff_latitude)],
        passenger_count=[int(passenger_count)]
        ))

model.predict(X)

array([11.8692708])

In [18]:
import requests

# fill the parameters for the prediction
x = dict(
  key='2012-10-06 12:10:20.0000001',
  pickup_datetime='2012-10-06 12:10:20 UTC',
  pickup_longitude=40.7614327,
  pickup_latitude=-73.9798156,
  dropoff_longitude=40.6413111,
  dropoff_latitude=-73.9797156,
  passenger_count=1
)

x = dict(
  key='2012-10-06 12:10:20.0000001',
  pickup_datetime='2012-10-06 12:10:20 UTC',
  pickup_longitude=40.7614327,
  pickup_latitude=-73.9798156,
  dropoff_longitude=40.6331166,
  dropoff_latitude=-73.8874078,
  passenger_count=2
)

# build the URL (server DNS, port, API endpoint, parameters)
# http://127.0.0.1:8000/predict_fare/2012-10-06%2012:10:20.0000001/2009-06-15%2017:26:21%20UTC/40.7614327/-73.9798156/40.6513111/-73.8803331/2
# taxifare_api_url = f"http://127.0.0.1:8000/predict_fare/{x['key']}/{x['pickup_datetime']}/{x['pickup_longitude']}/{x['pickup_latitude']}/{x['dropoff_longitude']}/{x['dropoff_latitude']}/{x['passenger_count']}"
# taxifare_api_url = f"http://127.0.0.1:8000/predict_fare/?key={x['key']}&pickup_datetime={x['pickup_datetime']}&pickup_longitude={x['pickup_longitude']}&pickup_latitude={x['pickup_latitude']}&dropoff_longitude={x['dropoff_longitude']}&dropoff_latitude={x['dropoff_latitude']}&passenger_count={x['passenger_count']}"
taxifare_api_url = "http://127.0.0.1:8000/predict_fare/?key=2012-10-06 12:10:20.0000001&pickup_datetime=2012-10-06 12:10:20 UTC&pickup_longitude=40.7614327&pickup_latitude=-73.9798156&dropoff_longitude=40.6513111&dropoff_latitude=-73.8803331&passenger_count=2"          

# retrieve the response
response = requests.get(taxifare_api_url).json()

print(response)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [19]:
from api.fast import create_fare

In [27]:
create_fare(a, b, c, d, e, f, g)

=> pipeline downloaded from storage

AttributeError: 'ColumnTransformer' object has no attribute '_has_str_cols'

In [25]:
a, b, c, d, e, f, g = x.values()